service: sls-strapi
provider:
  name: aws
  runtime: nodejs12.x
  logRetentionInDays: ${self:custom.vars.logRetentionInDays, 1}
  lambdaHashingVersion: "20201221"
  environment:
    ADMIN_JWT_SECRET: ${env:ADMIN_JWT_SECRET}
    DATABASE_URL: ${env:DATABASE_URL}
    ALGOLIA_KEY: ${self:custom.algolia-key}
    #AWS_ACCESS_KEY_ID: "my key"
    #AWS_SECRET_ACCESS_KEY: "my key"

package:
  patterns:
    - "!node_modules/**"
    #- "node_modules/strapi-hook-algolia/**"
    #- "node_modules/strapi-plugin-graphql/**"
    - "!tmp/**"
    - "!.cache/**"
    - "!.git/**"
    - "!build/**"
    - "!public/uploads/**"
    - api/**
    - config/**
    - exports/**
    - extensions/**
    - app-graphql.js
    - middlewares/**
    - plugins/**
    - package.json

functions:
  api:
    name: dev-auto-finance-api
    handler: app-graphql.handler
    #memorySize: 1024
    timeout: 120
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 15002
  algolia-key: ${env:ALGOLIA_KEY, ''}
